name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12, 14, 15]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install --ignore-scripts
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm run test --if-present<% } if (features.includes('test')) { %>
      - run: npx codecov<% } %>

  # publish:
  #   if: startsWith(github.ref, 'refs/tags')
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         registry-url: https://registry.npmjs.org
  #     - run: npm install --ignore-scripts
  #     - run: npm run build --if-present
  #     - run: npm publish --ignore-scripts
  #       env:
  #         NODE_AUTH_TOKEN: <%= '${{ secrets.NPM_TOKEN }}' %>
  #
  #     - uses: actions/setup-node@v2
  #       with:
  #         registry-url: https://npm.pkg.github.com
  #     - run: npm publish --ignore-scripts
  #       env:
  #         NODE_AUTH_TOKEN: <%= '${{ secrets.GITHUB_TOKEN }}' %>
